version: '3.8'
services:

  sealab:
    restart: always
    build:
      context: .
      dockerfile: docker/sealab/Dockerfile
    container_name: seaconex
    ports:
      - 8888:8888
    volumes:
      - ./notebooks/:/home/jovyan/work/notebooks
      - ./data/:/home/jovyan/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes

  searoute:
    build:
      context: .
      dockerfile: docker/searoute/Dockerfile
    container_name: searoute
    volumes:
      - ./data/searoute/data/:/data